# Generated by Django 5.0.6 on 2025-08-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_instagram',
            field=models.CharField(blank=True, help_text='Ex: @empresajr', max_length=100, null=True),
        ),
    ]
